### ISSUE TITLE
PHP ERROR : activation OnlyHardStates

### ISSUE THREAD

**Issue by centreon** [centreon/centreon-nagvis#3]
Julien Coerch Write : 

Bonjour,

J'ai installé le connecteur Nagvis/Centreon broker comme précisé dans la procédure.
Tout fonctionne correctement sauf quand je passe mais hôtes en "Only hard state" (pour n'afficher que l'état consolidé).
Lorsque j'active cette option j'obtiens le message suivant :

Error: (0) Undefined index: last_hard_state (/usr/local/nagvis/share/server/core/classes/GlobalBackendcentreonbroker.php:266)#0 /usr/local/nagvis/share/server/core/classes/GlobalBackendcentreonbroker.php(266): nagvisExceptionErrorHandler(8, 'Undefined index...', '/usr/local/nagv...', 266, Array)
#1 /usr/local/nagvis/share/server/core/classes/CoreBackendMgmt.php(327): GlobalBackendcentreonbroker->getHostState(Array, 3, Array)
#2 /usr/local/nagvis/share/server/core/classes/CoreBackendMgmt.php(169): CoreBackendMgmt->fetchStateCounts('centreonbroker_...', 'hostState', 3, Array)
#3 /usr/local/nagvis/share/server/core/classes/GlobalIndexPage.php(161): CoreBackendMgmt->execute()
#4 /usr/local/nagvis/share/server/core/classes/CoreModOverview.php(52): GlobalIndexPage->parseMapsJson('map')
#5 /usr/local/nagvis/share/server/core/functions/index.php(120): CoreModOverview->handleAction()
#6 /usr/local/nagvis/share/server/core/ajax_handler.php(63): require('/usr/local/nagv...')
#7 {main}

Merci pour votre aide

**Comment by EChauve** [comment]
+1 Having the same issue.

**Comment by ErrafayM** [comment]
I'm having same issue, someone got a fix ?

**Comment by emaintenance** [comment]
Forcer l'état courant permet de ne pas avoir de message d'erreur.

Remplacer la ligne : 
$row['current_state'] = $row['last_hard_state'];
par :
$row['current_state'] = $row['current_state'];
